# Generated by Django 4.1 on 2023-05-23 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name=" : الاسم")),
                (
                    "subtitle",
                    models.CharField(max_length=100, verbose_name="نبذه عنك :"),
                ),
                (
                    "address",
                    models.CharField(max_length=50, verbose_name="المحافظه : "),
                ),
                (
                    "address_detail",
                    models.CharField(max_length=50, verbose_name="العنوان بالتفصيل : "),
                ),
                (
                    "number_phone",
                    models.CharField(max_length=50, verbose_name="الهاتف :"),
                ),
                (
                    "working_hours",
                    models.CharField(max_length=10, verbose_name="عدد ساعات العمل :"),
                ),
                (
                    "Waiting_hours",
                    models.IntegerField(verbose_name="عدد دقائق الانتظار :"),
                ),
                ("doctor", models.CharField(max_length=50, verbose_name="دكتور ؟")),
                ("who_i", models.TextField(max_length=250, verbose_name=": من انا")),
                ("price", models.IntegerField(verbose_name=": سعر الكشف")),
                ("facebook", models.CharField(blank=True, max_length=100, null=True)),
                ("twitter", models.CharField(blank=True, max_length=100, null=True)),
                ("google", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_doctors",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "join_us",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت الانضمام"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile",
                        verbose_name="الصوره الشخصيه",
                    ),
                ),
                (
                    "specialist_doctor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="متخصص في ؟"
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="slug")),
                (
                    "rating",
                    models.PositiveIntegerField(default=0, verbose_name="التقييم"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
