# Generated by Django 4.1 on 2023-05-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_join_us_profile_manual_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="rating",
        ),
    ]
