# Generated by Django 4.1 on 2023-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_manual_datetime_profile_join_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="surname",
            field=models.CharField(default=1, max_length=80, verbose_name=" : اللقب"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("عظام", "عظام"),
                    ("أمراض دم", "أمراض دم"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("نفسي", "نفسي"),
                    ("أورام", "أورام"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("باطنة", "باطنة"),
                    ("أسنان", "أسنان"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("جلدية", "جلدية"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("نساء وتوليد", "نساء وتوليد"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
