# Generated by Django 4.1 on 2023-05-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_profile_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("جلدية", "جلدية"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("أمراض دم", "أمراض دم"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("نفسي", "نفسي"),
                    ("باطنة", "باطنة"),
                    ("أسنان", "أسنان"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("أورام", "أورام"),
                    ("عظام", "عظام"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الإسم")),
                ("number", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                ("email", models.EmailField(max_length=50, verbose_name="الإيميل")),
                (
                    "read",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="تمت القراءة"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc",
                        to="accounts.profile",
                        verbose_name="doctor",
                    ),
                ),
            ],
        ),
    ]
