# Generated by Django 4.1 on 2023-05-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_profile_doctor_delete_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("أمراض دم", "أمراض دم"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("عظام", "عظام"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("باطنة", "باطنة"),
                    ("أورام", "أورام"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("جلدية", "جلدية"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("أسنان", "أسنان"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("نفسي", "نفسي"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("جراحة تجميل", "جراحة تجميل"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الإسم")),
                ("number", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                ("email", models.EmailField(max_length=50, verbose_name="الإيميل")),
                (
                    "read",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="تمت القراءة"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc",
                        to="accounts.profile",
                        verbose_name="doctor",
                    ),
                ),
            ],
        ),
    ]
