# Generated by Django 4.1 on 2023-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_profile_doctor_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("أسنان", "أسنان"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("أورام", "أورام"),
                    ("باطنة", "باطنة"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("نفسي", "نفسي"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("أمراض دم", "أمراض دم"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("جلدية", "جلدية"),
                    ("عظام", "عظام"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default=1, upload_to="static/profile", verbose_name="الصوره الشخصيه"
            ),
            preserve_default=False,
        ),
    ]
