# Generated by Django 4.1 on 2023-05-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_profile_doctor_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("أمراض دم", "أمراض دم"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("أورام", "أورام"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("باطنة", "باطنة"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("جلدية", "جلدية"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("عظام", "عظام"),
                    ("أسنان", "أسنان"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("نفسي", "نفسي"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="profile", verbose_name="الصوره الشخصيه"),
        ),
    ]
