# Generated by Django 4.1 on 2023-05-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_profile_doctor_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="Receipt_number",
            field=models.CharField(
                default=1, max_length=20, verbose_name="رقم الايصال"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("أسنان", "أسنان"),
                    ("عظام", "عظام"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("باطنة", "باطنة"),
                    ("جلدية", "جلدية"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("أمراض دم", "أمراض دم"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("أورام", "أورام"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("نفسي", "نفسي"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
