# Generated by Django 4.1 on 2023-06-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_appointment_receipt_number_alter_profile_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("عظام", "عظام"),
                    ("باطنة", "باطنة"),
                    ("أسنان", "أسنان"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("جلدية", "جلدية"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("أورام", "أورام"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("نفسي", "نفسي"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("أمراض دم", "أمراض دم"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
