# Generated by Django 4.1 on 2023-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_profile_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="read",
            field=models.BooleanField(default=1, verbose_name="تمت القراءة"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("نفسي", "نفسي"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("باطنة", "باطنة"),
                    ("عظام", "عظام"),
                    ("جلدية", "جلدية"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("أمراض دم", "أمراض دم"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("أورام", "أورام"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("أسنان", "أسنان"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
