# Generated by Django 4.1 on 2023-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_appointment_read_alter_profile_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="read",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="تمت القراءة"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("جراحة أورام", "جراحة أورام"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("أسنان", "أسنان"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                    ("أمراض دم", "أمراض دم"),
                    ("جلدية", "جلدية"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("نفسي", "نفسي"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("باطنة", "باطنة"),
                    ("عظام", "عظام"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("أورام", "أورام"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
