# Generated by Django 4.1 on 2023-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_appointment_read_alter_profile_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="Receipt_number",
            new_name="Receipt",
        ),
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("أسنان", "أسنان"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("عظام", "عظام"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("جلدية", "جلدية"),
                    ("نفسي", "نفسي"),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("باطنة", "باطنة"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("أمراض دم", "أمراض دم"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("أورام", "أورام"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
