# Generated by Django 4.1 on 2023-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_rename_receipt_number_appointment_receipt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="doctor",
            field=models.CharField(
                choices=[
                    ("أورام", "أورام"),
                    ("قلب وأوعيه دموية", "قلب وأوعيه دموية"),
                    ("نفسي", "نفسي"),
                    ("جراحة أورام", "جراحة أورام"),
                    ("جراحة سمنة ومناظير ", "جراحة سمنة ومناظير "),
                    ("مخ وأعصاب", "مخ وأعصاب"),
                    ("عظام", "عظام"),
                    ("تخسيس وتغذية", "تخسيس وتغذية"),
                    ("باطنة", "باطنة"),
                    ("نساء وتوليد", "نساء وتوليد"),
                    ("جلدية", "جلدية"),
                    ("أنف وأذن وحنجرة", "أنف وأذن وحنجرة"),
                    ("جراحة تجميل", "جراحة تجميل"),
                    ("جراحة أطفال", "جراحة أطفال"),
                    ("أطفال حديثي الولادة", "أطفال حديثي الولادة"),
                    ("أسنان", "أسنان"),
                    ("أمراض دم", "أمراض دم"),
                    ("جراحة أوعيه دموية", "جراحة أوعيه دموية"),
                ],
                max_length=50,
                verbose_name="دكتور ؟",
            ),
        ),
    ]
